development:
  host: 50.16.191.161
  database: TweetFlick

test:
  host: localhost
  database: TweetFlick

# set these environment variables on your prod server
production:
  host: 50.16.191.161
  #<%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  database: TweetFlick
  #<%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

